spring:
  application:
    name: jiguang-sdk

server:
  port: 9876

logging:
  level:
    root: debug

jiguang:
  api:
    # 此为演示数据，请替换成真实数据
    app-key: b266cd5c8544ba09b23733e3
    master-secret: 15747d3881d308fe5107b7da
    dev-key: c2dc75e97486529205528b23
    dev-secret: d219e2f001df2fe4f08b6754
    group-key: 2ed1465b94aab3f03f6778e0
    group-master-secret: 5b69dce5f9dc0dabe70aa33a


