name: Publish package to the Maven Central Repository
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: 'central'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_PASSWORD }}
      - name: Publish package
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: mvn --batch-mode -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_PASSWORD }} clean deploy -am -pl jiguang-sdk -X
